In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline 
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_auc_score

In [2]:
df=pd.read_csv(r"C:\Users\sarkar\Desktop\final\all about projects\churn prediction\insurance churn prediction\data\Insurance_Churn_ParticipantsData\Train.csv")

In [3]:
dffeature=df.copy()

In [4]:
dff=dffeature.drop(['feature_7','feature_10'],axis=1)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=dff.drop("labels",axis=1)
y=dff.labels

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [8]:
from sklearn.ensemble import AdaBoostClassifier
model1 = AdaBoostClassifier()

In [9]:
model1.fit(X_train, y_train)

AdaBoostClassifier()

In [10]:

predtrain=model1.predict(X_train)
predtest=model1.predict(X_test)

In [11]:
def performa(y,y_pred):
    confusion=confusion_matrix(y, y_pred)
    accuracy=accuracy_score(y, y_pred)
    precision=precision_score(y, y_pred)
    recall=recall_score(y, y_pred)
    ROC_AUC=roc_auc_score(y, y_pred)
    print("confusion_matrix\n",confusion)
    print("accuracy: ",accuracy)
    print("precision: ",precision)
    print("recall: ",recall)
    print("ROC_AUC: ",ROC_AUC)

# Train

In [12]:
performa(y_train,predtrain)

confusion_matrix
 [[23218   738]
 [ 2055  1115]]
accuracy:  0.8970360539703606
precision:  0.6017269293038316
recall:  0.35173501577287064
ROC_AUC:  0.6604642686144367


# Test 

In [13]:
performa(y_test,predtest)

confusion_matrix
 [[5816  169]
 [ 516  281]]
accuracy:  0.898997345915659
precision:  0.6244444444444445
recall:  0.35257214554579674
ROC_AUC:  0.6621674428647947


# Tuning 

In [15]:
from sklearn.model_selection import GridSearchCV
param_grid={
	'n_estimators':[100,200],
	'learning_rate':[0.001,0.01,0.1,0.2,0.5]
}
gs_ab=GridSearchCV(AdaBoostClassifier(),param_grid=param_grid)

In [17]:
gs_ab.fit(X_train,y_train)

GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 0.2, 0.5],
                         'n_estimators': [100, 200]})

In [18]:
gs_ab.best_estimator_

AdaBoostClassifier(learning_rate=0.5, n_estimators=200)

In [19]:
model2=AdaBoostClassifier(learning_rate=0.5, n_estimators=200)

In [21]:
model2.fit(X_train,y_train)

AdaBoostClassifier(learning_rate=0.5, n_estimators=200)

In [22]:
predtrain=model2.predict(X_train)
predtest=model2.predict(X_test)

# Train 

In [23]:
performa(y_train,predtrain)

confusion_matrix
 [[23312   644]
 [ 2019  1151]]
accuracy:  0.9018285040182851
precision:  0.6412256267409471
recall:  0.36309148264984226
ROC_AUC:  0.668104432258299


# Test 

In [24]:
performa(y_test,predtest)

confusion_matrix
 [[5836  149]
 [ 503  294]]
accuracy:  0.9038631672073135
precision:  0.6636568848758465
recall:  0.36888331242158096
ROC_AUC:  0.6719938700787937


In [26]:
from sklearn.model_selection import cross_val_score
cross_val_score(model2, X_train, y_train,cv=5).mean()

0.8997271576858987

In [27]:
cross_val_score(model2, X_test, y_test,cv=5).mean()

0.9012071135573656

In [28]:
accuracy=[0.9038631672073135,0.9018285040182851]
precision=[0.6636568848758465,0.6412256267409471]
recall=[0.36888331242158096,0.36309148264984226]
ROC=[0.6719938700787937,0.668104432258299]
cross_val=[0.9012071135573656,0.8997271576858987]
df_final_performa=pd.DataFrame({"accuracy":accuracy,
                               "precision":precision,
                               "recall":recall,
                               "ROC":ROC,
                               "cross_val":cross_val},index={"test","train"})

In [29]:
df_final_performa

accuracy  precision    recall       ROC  cross_val
train  0.903863   0.663657  0.368883  0.671994   0.901207
test   0.901829   0.641226  0.363091  0.668104   0.899727

In [30]:
dff.columns

Index(['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_8', 'feature_9', 'feature_11',
       'feature_12', 'feature_13', 'feature_14', 'feature_15', 'labels'],
      dtype='object')