In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline 
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_auc_score

In [2]:
df=pd.read_csv(r"C:\Users\sarkar\Desktop\final\all about projects\churn prediction\insurance churn prediction\data\Insurance_Churn_ParticipantsData\Train.csv")

In [3]:
dffeature=df.copy()

In [4]:
dff=dffeature.drop(['feature_7','feature_10'],axis=1)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=dff.drop("labels",axis=1)
y=dff.labels

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn import tree
model1 = tree.DecisionTreeClassifier()

In [9]:
model1.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:

predtrain=model1.predict(X_train)
predtest=model1.predict(X_test)


In [11]:
def performa(y,y_pred):
    confusion=confusion_matrix(y, y_pred)
    accuracy=accuracy_score(y, y_pred)
    precision=precision_score(y, y_pred)
    recall=recall_score(y, y_pred)
    ROC_AUC=roc_auc_score(y, y_pred)
    print("confusion_matrix\n",confusion)
    print("accuracy: ",accuracy)
    print("precision: ",precision)
    print("recall: ",recall)
    print("ROC_AUC: ",ROC_AUC)

# Train 

In [12]:
performa(y_train,predtrain)

confusion_matrix
 [[20069     0]
 [    0  2649]]
accuracy:  1.0
precision:  1.0
recall:  1.0
ROC_AUC:  1.0


# Test

In [13]:
performa(y_test,predtest)

confusion_matrix
 [[9161  711]
 [ 711  607]]
accuracy:  0.8729222520107238
precision:  0.460546282245827
recall:  0.460546282245827
ROC_AUC:  0.6942622010904986


# Tuning 

In [14]:
from sklearn.model_selection import GridSearchCV 
from sklearn.metrics import f1_score, make_scorer
  
parameters = {'max_depth':[1,2,3,4,5], 'min_samples_leaf':[1,2,3,4,5], 'min_samples_split':[2,3,4,5], 'criterion' : ['gini','entropy']}
scorer = make_scorer(f1_score)

In [15]:
grid_obj = GridSearchCV(model1, parameters, scoring=scorer)

In [16]:

grid_fit = grid_obj.fit(X_train, y_train)

In [17]:
grid_fit.best_estimator_

DecisionTreeClassifier(max_depth=5, min_samples_leaf=3)

In [18]:
model2=tree.DecisionTreeClassifier(max_depth=5, min_samples_leaf=3)

In [19]:
model2.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=3)

In [21]:

predtrain=model2.predict(X_train)
predtest=model2.predict(X_test)

# Train 

In [22]:
performa(y_train,predtrain)

confusion_matrix
 [[19585   484]
 [ 1693   956]]
accuracy:  0.9041729025442381
precision:  0.6638888888888889
recall:  0.36089090222725556
ROC_AUC:  0.6683870525885393


# Test 

In [23]:
performa(y_test,predtest)

confusion_matrix
 [[9626  246]
 [ 865  453]]
accuracy:  0.9007149240393209
precision:  0.648068669527897
recall:  0.34370257966616086
ROC_AUC:  0.6593918084716541


In [27]:
from sklearn.model_selection import cross_val_score
cross_val_score(tree.DecisionTreeClassifier(max_depth=5, min_samples_leaf=3), X_train, y_train,cv=5).mean()

0.9000794636850378

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(tree.DecisionTreeClassifier(max_depth=5, min_samples_leaf=3), X_test, y_test,cv=5).mean()

0.895710455764075

In [29]:
accuracy=[0.9007149240393209,0.9041729025442381]
precision=[0.648068669527897,0.6638888888888889]
recall=[0.34370257966616086,0.36089090222725556]
ROC=[0.6593918084716541,0.6683870525885393]
cross_val=[0.895710455764075,0.895710455764075]
df_final_performa=pd.DataFrame({"accuracy":accuracy,
                               "precision":precision,
                               "recall":recall,
                               "ROC":ROC,
                               "cross_val":cross_val},index={"test","train"})

In [30]:
df_final_performa

accuracy  precision    recall       ROC  cross_val
test   0.900715   0.648069  0.343703  0.659392    0.89571
train  0.904173   0.663889  0.360891  0.668387    0.89571