In [6]:
#Standardize the Variables
#Because the KNN classifier predicts the class of a given test observation
#by identifying the observations that are nearest to it, the scale of the 
#variables matters. Any variables that are on a large scale will have a much 
#larger effect on the distance between the observations, and hence on the KNN 
#classifier, than variables that are on a small scale.

In [15]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline 
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_auc_score

In [2]:
df=pd.read_csv(r"C:\Users\sarkar\Desktop\final\all about projects\churn prediction\insurance churn prediction\data\Insurance_Churn_ParticipantsData\Train.csv")

In [3]:
dffeature=df.copy()

In [4]:
dff=dffeature.drop(['feature_7','feature_10'],axis=1)

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X=dff.drop("labels",axis=1)
y=dff.labels

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
Model1 = KNeighborsClassifier(n_neighbors=1)

In [13]:
Model1.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [14]:
y_pred=Model1.predict(X_train)

In [16]:
def performa(y,y_pred):
    confusion=confusion_matrix(y, y_pred)
    accuracy=accuracy_score(y, y_pred)
    precision=precision_score(y, y_pred)
    recall=recall_score(y, y_pred)
    ROC_AUC=roc_auc_score(y, y_pred)
    print("confusion_matrix\n",confusion)
    print("accuracy: ",accuracy)
    print("precision: ",precision)
    print("recall: ",recall)
    print("ROC_AUC: ",ROC_AUC)

# Model score Train

In [17]:
performa(y_train,y_pred)

confusion_matrix
 [[20069     0]
 [    0  2649]]
accuracy:  1.0
precision:  1.0
recall:  1.0
ROC_AUC:  1.0


# Test

In [19]:
ytest_pred=Model1.predict(X_test)

In [20]:
performa(y_test,ytest_pred)

confusion_matrix
 [[9269  603]
 [ 741  577]]
accuracy:  0.8798927613941019
precision:  0.48898305084745763
recall:  0.4377845220030349
ROC_AUC:  0.6883513371765579


In [21]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors':np.arange(1,50)}
knn = KNeighborsClassifier()
knn_cv= GridSearchCV(knn,param_grid,cv=5)
knn_cv.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])})

In [22]:
print("Best Score:" + str(knn_cv.best_score_))
print("Best Parameters: " + str(knn_cv.best_params_))

Best Score:0.9011443757256938
Best Parameters: {'n_neighbors': 13}


In [23]:
Model2 = KNeighborsClassifier(n_neighbors=13)

In [24]:
Model2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

# Train

In [25]:
y_pred=Model2.predict(X_train)

In [26]:
performa(y_train,y_pred)

confusion_matrix
 [[19699   370]
 [ 1658   991]]
accuracy:  0.9107315784840215
precision:  0.7281410727406319
recall:  0.37410343525858814
ROC_AUC:  0.6778335204097017


# Test 

In [27]:
ytest_pred=Model2.predict(X_test)

In [28]:
performa(y_test,ytest_pred)

confusion_matrix
 [[9628  244]
 [ 880  438]]
accuracy:  0.8995531724754244
precision:  0.6422287390029325
recall:  0.3323216995447648
ROC_AUC:  0.6538026650073906


# Cross validation 

In [39]:
from sklearn.model_selection import cross_val_score
cross_val_score(Model2, X_train, y_train,cv=5).mean()

0.8989788306107833

In [40]:
cross_val_score(Model2, X_test, y_test,cv=5).mean()

0.8983914209115282

In [42]:
accuracy=[0.8995531724754244,0.9107315784840215]
precision=[0.6422287390029325,0.7281410727406319]
recall=[0.3323216995447648,0.37410343525858814]
ROC=[0.6538026650073906,0.6778335204097017]
cross_val=[0.8983914209115282,0.8989788306107833]
df_final_performa=pd.DataFrame({"accuracy":accuracy,
                               "precision":precision,
                               "recall":recall,
                               "ROC":ROC,
                               "cross_val":cross_val},index={"test","train"})

In [43]:
df_final_performa

accuracy  precision    recall       ROC  cross_val
test   0.899553   0.642229  0.332322  0.653803   0.898391
train  0.910732   0.728141  0.374103  0.677834   0.898979