In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline 
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_auc_score

In [2]:
df=pd.read_csv(r"C:\Users\sarkar\Desktop\final\all about projects\churn prediction\insurance churn prediction\data\Insurance_Churn_ParticipantsData\Train.csv")

In [3]:
dffeature=df.copy()

In [4]:
dff=dffeature.drop(['feature_7','feature_10'],axis=1)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=dff.drop("labels",axis=1)
y=dff.labels

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.svm import SVC

model1 = SVC(kernel='linear') 
model1.fit(X_train,y_train)

SVC(kernel='linear')

In [10]:
predtrain=model1.predict(X_train)
predtest=model1.predict(X_test)

In [11]:
def performa(y,y_pred):
    confusion=confusion_matrix(y, y_pred)
    accuracy=accuracy_score(y, y_pred)
    precision=precision_score(y, y_pred)
    recall=recall_score(y, y_pred)
    ROC_AUC=roc_auc_score(y, y_pred)
    print("confusion_matrix\n",confusion)
    print("accuracy: ",accuracy)
    print("precision: ",precision)
    print("recall: ",recall)
    print("ROC_AUC: ",ROC_AUC)

# Train 

In [12]:
performa(y_train,predtrain)

confusion_matrix
 [[20069     0]
 [ 2649     0]]
accuracy:  0.8833964257417026
precision:  0.0
recall:  0.0
ROC_AUC:  0.5


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Test 

In [13]:
performa(y_test,predtest)

confusion_matrix
 [[9872    0]
 [1318    0]]
accuracy:  0.8822162645218945
precision:  0.0
recall:  0.0
ROC_AUC:  0.5


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Gridsearch 

In [14]:

from sklearn.model_selection import GridSearchCV

In [15]:
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]}

In [16]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)


Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................... C=0.1, gamma=1, total=  22.5s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   22.4s remaining:    0.0s


[CV] ................................... C=0.1, gamma=1, total=  21.6s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=  22.6s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=  22.8s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=  23.1s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   4.7s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   4.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   4.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .

[CV] ................................ C=10, gamma=0.001, total=   5.0s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=  31.6s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=  32.0s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=  32.2s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=  32.4s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=  32.6s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=  15.6s
[CV] C=100, gamma=0.1 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed: 16.0min finished


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [17]:

print(grid.best_estimator_)

SVC(C=10, gamma=0.1)


In [18]:
model2=SVC(C=10, gamma=0.1)

In [19]:
model2.fit(X_train,y_train)

SVC(C=10, gamma=0.1)

In [23]:
predtrain=model2.predict(X_train)
predtest=model2.predict(X_test)

In [24]:
performa(y_train,predtrain)

confusion_matrix
 [[19814   255]
 [  985  1664]]
accuracy:  0.9454177304340171
precision:  0.8671182907764461
recall:  0.6281615704039261
ROC_AUC:  0.8077277033344061


In [25]:
performa(y_test,predtest)

confusion_matrix
 [[9550  322]
 [ 770  548]]
accuracy:  0.9024128686327078
precision:  0.6298850574712643
recall:  0.4157814871016692
ROC_AUC:  0.6915819915249027


In [27]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(C=10, gamma=0.1), X_train, y_train,cv=5).mean()

0.9009155859657172

In [28]:
cross_val_score(SVC(C=10, gamma=0.1), X_test, y_test,cv=5).mean()

0.8968722073279715

In [31]:
accuracy=[0.9024128686327078,0.9454177304340171]
precision=[0.6298850574712643,0.8671182907764461]
recall=[0.4157814871016692,0.6281615704039261]
ROC=[0.6915819915249027,0.8077277033344061]
cross_val=[0.8968722073279715,0.9009155859657172]
df_final_performa=pd.DataFrame({"accuracy":accuracy,
                               "precision":precision,
                               "recall":recall,
                               "ROC":ROC,
                               "cross_val":cross_val},index={"test","train"})

In [32]:
df_final_performa

accuracy  precision    recall       ROC  cross_val
test   0.902413   0.629885  0.415781  0.691582   0.896872
train  0.945418   0.867118  0.628162  0.807728   0.900916